version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Puertos de la API
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "80:80"      # Puertos del frontend
    restart: always
