# Etapa de construcción
FROM node:18.17.0 AS build

WORKDIR /app

COPY front/package*.json ./
RUN npm install

COPY front/ .

RUN npm run build

# Etapa final
FROM nginx:alpine

COPY --from=build /app/dist/front /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
