# Etapa de construcción
FROM node:latest as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Construir la aplicación Angular para producción
RUN npm run build --prod

# Etapa de producción
FROM nginx:alpine

# Copiar los archivos generados en la etapa de construcción
COPY --from=build /app/dist/front/browser /usr/share/nginx/html

# Exponer el puerto en el que el servidor Nginx escuchará
EXPOSE 8080:4200




# Comando para iniciar el servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
