# Etapa de construcción
FROM node:18.17.0 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --prod

# Etapa de producción
FROM nginx:alpine

COPY --from=build /app/dist/front/browser /usr/share/nginx/html

EXPOSE 8080

USER nginx


CMD ["nginx", "-g", "daemon off;"]
