name: Node.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0  # Ajusta según tu versión necesaria

      - name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: "1b9d6eca-f0f1-414e-ba90-3d334fabcd3d"
          heroku_app_name: "ayuntamiento"
          email: "alvaroados4b16@gmail.com"
          dockerfile_directory: "./"  # Directorio donde se encuentra el Dockerfile, ajusta según tu estructura de archivos
          dockerfile_name: "Dockerfile"  # Nombre de tu Dockerfile
          process_type: "web"
