name: Node.js

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0 

      - name: Deploy to Heroku - Frontend
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: "1b9d6eca-f0f1-414e-ba90-3d334fabcd3d"
          heroku_app_name: ayuntamiento
          email: alvaroados4b16@gmail.com
          dockerfile_directory: ayuntamiento/front  
          dockerfile_name: Dockerfile  
          process_type: web  

      - name: Deploy to Heroku - API
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: "1b9d6eca-f0f1-414e-ba90-3d334fabcd3d"
          heroku_app_name: ayuntamiento
          email: alvaroados4b16@gmail.com
          dockerfile_directory: ayuntamiento/api  
          dockerfile_name: Dockerfile  
          process_type: web  

      - name: Deploy to Heroku with docker-compose
        run: docker-compose -f docker-compose.yml up -d
