name: Despliegue en Heroku

on:
  push:
    branches:
      - main  # Cambia por la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Build y Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tu-usuario/heroku-api:latest   # Etiqueta para la API
            tu-usuario/heroku-frontend:latest  # Etiqueta para el frontend
          dockerfile: |
            Dockerfile  # Dockerfile para la API
            Dockerfile-front  # Dockerfile para el frontend

      - name: Login a Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ --password-stdin registry.heroku.com

      - name: Desplegar en Heroku
        run: |
          docker push tu-usuario/heroku-api:latest
          docker push tu-usuario/heroku-frontend:latest
          heroku container:release -a nombre-de-tu-app web   # Cambia 'nombre-de-tu-app' por el nombre de tu app en Heroku
