name: Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0  # Ajusta según tu versión necesaria

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            registry.heroku.com/ayuntamiento/web-front
            registry.heroku.com/ayuntamiento/web-api
          dockerfile: |
            ayuntamiento/front/Dockerfile
            ayuntamiento/api/Dockerfile

      - name: Login to Heroku Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ --password-stdin registry.heroku.com

      - name: Deploy to Heroku
        run: |
          docker push registry.heroku.com/ayuntamiento/web-front
          docker push registry.heroku.com/ayuntamiento/web-api
          heroku container:release web-front web-api --app ayuntamiento
