
name: Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0  # Cambiado a una versión más común, ajusta según tus necesidades

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku auth:token: "HRKU-673fd54b-8f12-4440-8cae-b9ead41f3239"
          heroku_app_name: "ayuntamiento"
          heroku_email: "alvaroados4b16@gmail.com"

