name: Node.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0  # Cambiado a una versión más común, ajusta según tus necesidades

      - name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ayuntamiento"
          email: "alvaroados4b16@gmail.com"
          dockerfile_directory: "./"  # Directorio donde se encuentra el Dockerfile, ajusta según tu estructura de archivos
          dockerfile_name: "Dockerfile"  # Nombre de tu Dockerfile
          docker_options: "--no-cache"
          process_type: "web"
