name: Despliegue en Heroku

on:
  push:
    branches:
      - master  # Aquí puedes cambiar el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Loguearse en Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ -p $(heroku auth:token) registry.heroku.com

      - name: Construir y subir contenedor de Frontend
        run: |
          docker build -t registry.heroku.com/ayuntamiento/web-front ./ayuntamiento/front
          docker push registry.heroku.com/ayuntamiento/web-front

      - name: Construir y subir contenedor de API
        run: |
          docker build -t registry.heroku.com/ayuntamiento/web-api ./ayuntamiento/api
          docker push registry.heroku.com/ayuntamiento/web-api

      - name: Desplegar en Heroku
        run: |
          heroku container:release web-front web-api --app ayuntamiento
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
